# Generated by Django 3.2 on 2021-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Toliq Ismingiz')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
                ('message', models.TextField(max_length=500, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
    ]
