# Generated by Django 3.2 on 2021-07-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Toliq Ismingiz')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
                ('message', models.TextField(max_length=500, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('muddat', models.CharField(max_length=50, verbose_name="O'qish muddati")),
                ('body', models.TextField(verbose_name='Kurs xaqida qisaqacha malumot')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Rasmi')),
                ('tajribasi', models.CharField(max_length=50, verbose_name='Ish Tajribasi')),
                ('natijasi', models.CharField(max_length=50, verbose_name='Natijasi')),
                ('body', models.TextField(verbose_name='Qisqacha Malumot')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Rasmi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name='Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.category')),
            ],
        ),
    ]
