# Generated by Django 3.2 on 2021-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_yangiliklar_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='body',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
    ]
