# Generated by Django 3.2 on 2021-07-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210715_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yangiliklar',
            new_name='Blog',
        ),
    ]
