# Generated by Django 3.2 on 2021-07-21 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cours_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images/', verbose_name='Rasmi'),
            preserve_default=False,
        ),
    ]
