# Generated by Django 3.2 on 2021-07-22 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Kurs xaqida qisaqacha malumot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='muddat',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name="O'qish muddati"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='*'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
    ]
