# Generated by Django 3.2 on 2021-07-22 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210722_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images/', verbose_name='Rasmi'),
            preserve_default=False,
        ),
    ]
